#ifndef SMDDRV_H_INCLUDED
#define SMDDRV_H_INCLUDED

#include "include/PDll.h"


class SMDDll: public PDLL
{
   DECLARE_CLASS(SMDDll);
   DECLARE_FUNCTION1(BOOL, SMD_OpenComPort, INT32 );
   DECLARE_FUNCTION0(BOOL, SMD_CloseComPort );
   DECLARE_FUNCTION0(INT32,  SMD_GetPortNumber );
   DECLARE_FUNCTION1(void, SMD_SetPortNumber, INT32 );
   DECLARE_FUNCTION0(char*, SMD_ErrMsg );
   DECLARE_FUNCTION2(BOOL, SMD_OnSHD, BYTE , INT32 );
   DECLARE_FUNCTION2(BOOL, SMD_OffSHD, BYTE , INT32 );
   DECLARE_FUNCTION3(BOOL, SMD_WriteTactFreq, BYTE , INT32 , INT32 );
   DECLARE_FUNCTION1(BOOL, SMD_OnAllSHD, BYTE );
   DECLARE_FUNCTION1(BOOL, SMD_OffAllSHD, BYTE );
   DECLARE_FUNCTION1(BOOL, SMD_ClearStep, BYTE );
   DECLARE_FUNCTION3(BOOL, SMD_WriteMulty, BYTE , INT32 , INT32 );
   DECLARE_FUNCTION4(BOOL, SMD_WriteMarchIHoldICode, BYTE , INT32 , INT32 , INT32 );
   DECLARE_FUNCTION3(BOOL, SMD_WritePhaseMode, BYTE , INT32 , BYTE );
   DECLARE_FUNCTION3(BOOL, SMD_ResetSHD, BYTE , BOOL , BOOL );
   DECLARE_FUNCTION3(BOOL, SMD_SetState, BYTE , BOOL , BOOL );
   DECLARE_FUNCTION1(BOOL, SMD_GetInform, char* );
   DECLARE_FUNCTION0(INT32,  SMD_GetAddr);
   DECLARE_FUNCTION1(BOOL, SMD_SetAddr, BYTE );
   DECLARE_FUNCTION5(BOOL, SMD_SetMoveParam, BYTE , INT32 , BOOL , BOOL , LONG32 );
};


#endif // SMDDRV_H_INCLUDED
